name: Build and Publish
on:
  push:
    branches:
      - main

jobs:
  build_linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.1

      - name: Build for Linux amd64
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -o gt_linux .

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gt
          path: gt_linux


  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.1

      - name: Build for Windows amd64
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -o gt_windows.exe .

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gt.exe
          path: gt_windows.exe